services:
  postgres:
    image: postgres:16-alpine
    container_name: splitwise-db
    environment:
      POSTGRES_USER: splitwise
      POSTGRES_PASSWORD: splitwise
      POSTGRES_DB: splitwise
    ports:
      - "5433:5432"
    volumes:
      - splitwise_data:/var/lib/postgresql/data

volumes:
  splitwise_data:
