[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:backend"

[deploy]
startCommand = "npm run prisma:deploy && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

